### ISSUE TITLE
Sometimes copy link to clipboard fails

### ISSUE THREAD

**Issue by warmwaffles** [orta/GIFs#42]
I only notice it after using it a few times and searching that I right click on the image and copy to clipboard. Nothing really happens, right now the work around is to open in the browser and then copy the browser URL

**Comment by samsonjs** [comment]
Copy never works for me with the keyboard, only from the context menu. I'm not a Mac dev but I whipped this up and it works for me: https://github.com/samsonjs/GIFs/commit/8e7953cbd62796f191af18bbccc26df61d889363

**Comment by orta** [comment]
Looks good @samsonjs - want to PR it back in? I'll wait for a few more PRs to come by and then release a new build.

**Comment by samsonjs** [comment]
Ok @orta, submitted as #43.

**Comment by orta** [comment]
nicceeee
