### ISSUE TITLE
Copy GIFs directly to clipboard.

### ISSUE THREAD

**Issue by jBot-42** [orta/GIFs#53]
I figured out a somewhat hackish way to do this:

```objective-c
NSPasteboard *pasteboard = [NSPasteboard generalPasteboard];

[pasteboard clearContents];
[pasteboard setString:[NSString stringWithFormat:@"<img src='%@'></img>", GIF_URL] forType:NSPasteboardTypeHTML];
```

It works for ~~all~~ most apps that support pasting animated GIFs.

![]
(http://media3.giphy.com/media/tgfiK90M72hbO/giphy.gif)

**Comment by jBot-42** [comment]
Update: I found a better way.

When implementing `- (NSArray *)webView:(WebView *)sender contextMenuItemsForElement:(NSDictionary *)element defaultMenuItems:(NSArray *)defaultMenuItems` for the web view delegate, check if the `defaultMenuItems` contains an item called Copy Image and if so, add it to the menu you are returning. This will allow pasting GIFs into more apps, including Messages (eliminating the need for a Messages share button).

**Comment by orta** [comment]
> This will allow pasting GIFs into more apps, including Messages (eliminating the need for a Messages share button).

:tada:

**Comment by jBot-42** [comment]
![]
(http://media4.giphy.com/media/moyFGwMkE9nwI/giphy.gif)

**Comment by orta** [comment]
Hrm, I'm taking a look at this and I agree, this is definitely :+1:

**Comment by orta** [comment]
Got this in.
